application: i18ncdmx
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app

- url: /ws/.*
  script: _go_app

- url: /(.*)
  static_files: web/\1
  upload: web/.*

skip_files:
- ^\.git/.*$
- ^\.sass-cache/.*$
- ^node_modules/.*$
- ^web/components/.*$
- ^\.pub/.*$